server:
  port: 9090

spring:
  application:
    name: gateway

  # AUTOMATIC GATEWAY LOCATOR ROUTING
  # automatically maps and routes HTTP requests to destination service if request provided using service name ex.: http://localhost:9090/{registered-service-name}/{url-inside-service}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # to use lower case in URL ex.: http://localhost:9090/users-service/...
          lower-case-service-id: true

      # MANUAL GATEWAY LOCATOR ROUTING
      # predicate makes path 'localhost:9090/' access to uri 'localhost:9090/users-service/'
      routes[0]:
        id: users-home
        ## registered service name OR api address OR host name
        uri: lb://users-service/
        ##java8 predicates used to match HTTP request using headers or method and route to destination (its like if statement condition)
        ##if all predicate conditions match - route to url: lb://usersservice/api/v1/users/' (uri+path)
        predicates[0]: Path=/
        ##=GET, POST, PUT, DELETE
        predicates[1]: Method=GET
        ##filters - default filter method but we can write our own
        filters[0]: RemoveRequestHeader=Cookie
      #        filters[1]: RewritePath=/users-service/(?<segment>.*), /${segment}

      # user login route
      routes[1]:
        id: user-signin
        uri: lb://users-service
        predicates[0]: Path=/users-service/login
        predicates[1]: Method=POST
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: RewritePath=/users-service/(?< segment>.*), /${segment}

      # user register route
      routes[2]:
        id: user-signup
        uri: lb://users-service
        predicates[0]: Path=/users-service/register
        predicates[1]: Method=POST
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: RewritePath=/users-service/(?< segment>.*), /${segment}

  # rabbitMQ config for Spring Cloud Bus to be able to communicate
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    # password: guest
    password: '{cipher}AQC9lpXh3COldXHmKD2LEkHjtRpylXnMu9j9ikee+72wUg/Qj70CdZyRgThT7+DQF30JuPzw5UdVYayDYD4Hsw0iXYoDKIYpEJy31mbUuHPXVkuXS73PgCQZ6SvKN1HpXLE86S1Buvmp0TE5abbiebckJrXTNSDgYV7gvVxp1mjX47egwdWVZpe5DmifiLrnBOMVJffuczhGYFpeykEPPTPzLGqA7hJXdB+SR96RdBYS9V9HW/IIAjhE+bbu8h2mW0m72Gz0fDH7D8ppzk3PkGJZMoGN9zPlJiK1Z/m6IPP4Q1E1SnawVDIOkD1qZMV/+9e951Dz7YhUa61gUVF+een1QnZy3/TeplaLvmTIYy78lfs/HzpS0DMHtQuJK/jhM18='

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
